ersion: "3.7"

services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins:
